name: Count Every 30 Minutes
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  count-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Load Counter and Increment
      id: setup-counter
      run: |
        if [ ! -f counter.txt ]; then
          echo "0" > counter.txt
        fi
        counter=$(cat counter.txt)

        counter=$((counter + 1))
        echo "Counter value incremented to: $counter"

        echo "$counter" > counter.txt

        echo "::set-output name=counter::$counter"

      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Commit and Push Changes
      run: |
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_NAME }}"
        git pull
        git add counter.txt
        git commit -m "Increment counter to ${{ steps.setup-counter.outputs.counter }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
